version: '3'

services:
  postgres:
    image: postgres:16
    container_name: autopom-postgres-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-autopom}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - autopom-network

  redis:
    image: redis:7
    container_name: autopom-redis-prod
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis_prod_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - autopom-network

  api:
    build: ./fastapi-backend
    container_name: autopom-api-prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/${POSTGRES_DB:-autopom}
      - REDIS_URL=redis://default:${REDIS_PASSWORD:-redis}@redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://app.autopom.app,chrome-extension://*/}
    restart: always
    networks:
      - autopom-network
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000

  nginx:
    image: nginx:latest
    container_name: autopom-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - api
    restart: always
    networks:
      - autopom-network

networks:
  autopom-network:
    driver: bridge

volumes:
  postgres_prod_data:
  redis_prod_data: 